package com.mydb.services;

import com.mydb.utils.DatabaseConnection;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class BackupService {
    
    public static String exportDatabaseToSQL(String databaseName, String outputPath) throws SQLException, IOException {
        Connection conn = DatabaseConnection.getConnection(databaseName);
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String filename = outputPath + "/" + databaseName + "_backup_" + timestamp + ".sql";
        
        FileWriter writer = new FileWriter(filename);
        
        // Write header
        writer.write("-- MyDB Database Backup\n");
        writer.write("-- Database: " + databaseName + "\n");
        writer.write("-- Date: " + LocalDateTime.now() + "\n");
        writer.write("-- Generated by MyDB AI-Powered Database Manager\n\n");
        
        writer.write("CREATE DATABASE IF NOT EXISTS `" + databaseName + "`;\n");
        writer.write("USE `" + databaseName + "`;\n\n");
        
        // Get all tables
        DatabaseMetaData metaData = conn.getMetaData();
        ResultSet tables = metaData.getTables(databaseName, null, "%", new String[]{"TABLE"});
        
        while (tables.next()) {
            String tableName = tables.getString("TABLE_NAME");
            
            // Export table structure
            writer.write("-- Table structure for `" + tableName + "`\n");
            writer.write("DROP TABLE IF EXISTS `" + tableName + "`;\n");
            
            Statement stmt = conn.createStatement();
            ResultSet createTableRS = stmt.executeQuery("SHOW CREATE TABLE `" + tableName + "`");
            
            if (createTableRS.next()) {
                String createTableSQL = createTableRS.getString(2);
                writer.write(createTableSQL + ";\n\n");
            }
            
            // Export table data
            writer.write("-- Data for table `" + tableName + "`\n");
            
            ResultSet dataRS = stmt.executeQuery("SELECT * FROM `" + tableName + "`");
            ResultSetMetaData rsMetaData = dataRS.getMetaData();
            int columnCount = rsMetaData.getColumnCount();
            
            while (dataRS.next()) {
                StringBuilder insertSQL = new StringBuilder("INSERT INTO `" + tableName + "` VALUES (");
                
                for (int i = 1; i <= columnCount; i++) {
                    Object value = dataRS.getObject(i);
                    
                    if (value == null) {
                        insertSQL.append("NULL");
                    } else if (value instanceof String || value instanceof Date || value instanceof Timestamp) {
                        insertSQL.append("'").append(value.toString().replace("'", "''")).append("'");
                    } else {
                        insertSQL.append(value);
                    }
                    
                    if (i < columnCount) {
                        insertSQL.append(", ");
                    }
                }
                
                insertSQL.append(");\n");
                writer.write(insertSQL.toString());
            }
            
            writer.write("\n");
        }
        
        writer.write("-- Backup completed successfully\n");
        writer.close();
        
        return filename;
    }
    
    public static String exportTableToCSV(String databaseName, String tableName, String outputPath) 
            throws SQLException, IOException {
        
        Connection conn = DatabaseConnection.getConnection(databaseName);
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String filename = outputPath + "/" + tableName + "_export_" + timestamp + ".csv";
        
        FileWriter writer = new FileWriter(filename);
        
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM `" + tableName + "`");
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        // Write header
        for (int i = 1; i <= columnCount; i++) {
            writer.write(escapeCSV(metaData.getColumnName(i)));
            if (i < columnCount) writer.write(",");
        }
        writer.write("\n");
        
        // Write data
        while (rs.next()) {
            for (int i = 1; i <= columnCount; i++) {
                String value = rs.getString(i);
                writer.write(escapeCSV(value == null ? "" : value));
                if (i < columnCount) writer.write(",");
            }
            writer.write("\n");
        }
        
        writer.close();
        return filename;
    }
    
    public static String exportTableToJSON(String databaseName, String tableName, String outputPath) 
            throws SQLException, IOException {
        
        Connection conn = DatabaseConnection.getConnection(databaseName);
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String filename = outputPath + "/" + tableName + "_export_" + timestamp + ".json";
        
        FileWriter writer = new FileWriter(filename);
        
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * FROM `" + tableName + "`");
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        
        writer.write("[\n");
        
        boolean firstRow = true;
        while (rs.next()) {
            if (!firstRow) {
                writer.write(",\n");
            }
            firstRow = false;
            
            writer.write("  {\n");
            for (int i = 1; i <= columnCount; i++) {
                String columnName = metaData.getColumnName(i);
                String value = rs.getString(i);
                
                writer.write("    \"" + columnName + "\": ");
                
                if (value == null) {
                    writer.write("null");
                } else {
                    writer.write("\"" + escapeJSON(value) + "\"");
                }
                
                if (i < columnCount) writer.write(",");
                writer.write("\n");
            }
            writer.write("  }");
        }
        
        writer.write("\n]\n");
        writer.close();
        
        return filename;
    }
    
    private static String escapeCSV(String value) {
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
    
    private static String escapeJSON(String value) {
        return value.replace("\\", "\\\\")
                   .replace("\"", "\\\"")
                   .replace("\n", "\\n")
                   .replace("\r", "\\r")
                   .replace("\t", "\\t");
    }
}
